version: "3.9"
services:
  client:
    build: ../echo
    command: node /app/client.js server:10000
    volumes:
      - ../cert:/cert
    depends_on:
      server:
        condition: service_healthy
  server:
    build: ../echo
    command: node /app/server.js 0.0.0.0:10000
    ports:
      - "10000:10000"
    volumes:
      - ../cert:/cert
    healthcheck:
      test: "nc -v -z -w 1 localhost 10000 || exit 1"
      interval: 1s
      timeout: 1s
      start_period: 1s
